name: Jacques Fuentes
highlighter: pygments
markdown: rdiscount
markdown_ext: markdown,md
rdiscount:
  extensions: [smart]
timezone: America/New_York
port: 9292
excerpt_separator: "\n"
paginate: 5
exclude:
  - sass
  - .sass-cache
  - Procfile
