contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://jacquesfuentes.com"
canonifyurls = true
pygmentsuseclasses = true

[permalinks]
  essays = "/:year/:month/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # description = "Tesla's Awesome Hugo Site"
  author = "Jacques Fuentes"
